Do not ignore tests from test suite in the beginning but run all tests     and do not fail if dh_auto_test returns error.  Thus we keep a logfile     containing failed errors we can point upstream to

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -47,15 +47,26 @@ EXCLUDE_TESTS = not test_load_boston_alternative and \
 # is not solved
 EXCLUDE_TEST += and not sklearn.ensemble._weight_boosting.AdaBoostRegressor
 
+IGNORE_ERRORS=
+ERROR_LOG=record
+#we rather want to record the test suite errors in build log than ignoring the potentially failing tests
+ifeq ($(ERROR_LOG),ignore)
 # Some tests are known to fail randomly so need to be excluded ATM
 ifeq ($(DEB_HOST_ARCH),arm64)
   # A bit aggressive exclusion of some tests which exhibit a problem I have no time to deal with on arm64
   EXCLUDE_TESTS += and not test_dump
 endif
 
+# Its a shame that nobody cares for all architectures but we do not have the manpower to fix all tests
+ifeq ($(DEB_HOST_ARCH),armel)
+  # Ignored due to bug #1003165
+  EXCLUDE_TESTS += and not test_tfidf_no_smoothing
+endif
+
 # Until these are fixed:
 # https://github.com/scikit-learn/scikit-learn/issues/16443
 # https://github.com/scikit-learn/scikit-learn/issues/13052
+## armhf is in a really bad state,  The log says "Fatal Python error: Bus error".  This really needs to be investigated
 ifeq ($(DEB_HOST_ARCH),armhf)
   EXCLUDE_TESTS += and not test_check_estimators_stacking_estimator
   EXCLUDE_TESTS += and not test_check_estimators_voting_estimator
@@ -68,22 +79,39 @@ ifeq ($(DEB_HOST_ARCH),armhf)
   EXCLUDE_TESTS += and not test_common
 endif
 
+# Its a shame that nobody cares for all architectures but we do not have the manpower to fix all tests
+ifeq ($(DEB_HOST_ARCH),mips64el)
+  # Ignored due to bug #1003165
+  EXCLUDE_TESTS += and not test_lasso_lars_vs_R_implementation
+endif
+
 # TBD. See https://bugs.debian.org/967977
 ifeq ($(DEB_HOST_ARCH),s390x)
+  EXCLUDE_TESTS += and not test_gaussian_kde
   EXCLUDE_TESTS += and not test_gaussian_kde
 endif
 ifeq ($(DEB_HOST_ARCH),alpha)
   EXCLUDE_TESTS += and not test_gaussian_kde
 endif
+
 # Same test, but not entirely the same results as above. Assuming same cause
 ifeq ($(DEB_HOST_ARCH),i386)
   EXCLUDE_TESTS += and not test_gaussian_kde
   EXCLUDE_TESTS += and not test_y_multioutput
 endif
 
+
 # Until https://github.com/scikit-learn/scikit-learn/issues/19230 is open
 ifeq ($(DEB_HOST_ARCH),i368)
   EXCLUDE_TESTS += and not test_convergence_dtype_consistency
+endif
+
+else
+# for all architectures that are known to have failures in test suite we are ignoring these
+ifeq ($(DEB_HOST_ARCH),$(filter $(DEB_HOST_ARCH), i386 mipsel mips64el hppa armel armhf arm64 ppc64 ppc64el s390x alpha))
+  # Ignored due to bug #1003165
+IGNORE_ERRORS=" || true"
+endif
 endif
 
 # This is used by patch sphinx-doc-no-download.patch to prevent the sphinx
@@ -173,6 +201,10 @@ export PYBUILD_AFTER_TEST
 # Nothing to do for indep
 override_dh_auto_test-indep:
 
+
+override_dh_auto_test-arch:
+	dh_auto_test -a $(IGNORE_ERRORS)
+
 export PYBUILD_AFTER_INSTALL = rm -f {destdir}/{install_dir}/_configtest*
 override_dh_auto_install:
 	dh_auto_install
@@ -190,8 +222,9 @@ ifneq (,$(filter python-sklearn-doc,$(shell dh_listpackages)))
 	if [ -e $$docdir/stable ] ; then \
 	mv \
 		$$docdir/stable $$docdir/html; \
-    fi
+	fi
 endif
+	if [ -e debian/README.Debian.$(DEB_HOST_ARCH) ] ; then dh_installdocs -A debian/README.Debian.$(DEB_HOST_ARCH) ; fi
 
 override_dh_installchangelogs:
 	dh_installchangelogs doc/whats_new.rst
